# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DasHalloProjekt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DasHalloProjekt
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'DasHalloProjektTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DasHalloProjektUITests' do
    # Pods for testing
  end

end
